version: '3'
services:
  web:
    image: nginx:stable-alpine
    container_name: web.currency-converter
    environment:
      - VIRTUAL_HOST=currency-converter.albertokato.com
    expose:
      - '80'
    volumes:
      - './:/usr/share/nginx/html'
    restart: always

networks:
  default:
    external:
      name: main
